### ISSUE TITLE
커뮤니티 도메인 관련 Schema 추가

### ISSUE THREAD

**Issue by S-HoChan** [Laundry-Platform/Laundry_Core#16]
**Problem or enhancements and It's Background**
- 커뮤니티 도메인을 다루기 위한 작업을 수행한다.

**Solutions**
- schema.sql파일에 연관 스키마를 작성한다.

**TODO Tasks and Cautions**
- [x]  schema.sql 파일에 게시글(post) table 작성
- [x] schema.sql 파일에 리뷰(review) 작성
- [x] schema.sql 파일에 카테고리(category) 작성

**Comment by Dokyeongyun** [comment]
@S-HoChan 
Issue의 단위가 너무 큰 것 같아요.
커뮤니티 도메인과 관련된 테이블의 스키마를 추가하는 것을 해당 Issue의 목표로 설정합시다.

**Comment by S-HoChan** [comment]
수정했습니다
