### ISSUE TITLE
Laundry 테이블 스키마 추가 및 CRUD

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#31]
**Problem or enhancements and It's Background**
- laundry 테이블의 데이터를 CRUD 가능하게 하기 위함

**Solutions**
- laundry 테이블 schema 및 data 추가
- laundry 테이블의 데이터를 다룰 수 있는 인터페이스 생성
- Mapper 파일 내, Query 작성

**TODO Tasks and Cautions**
- [x] laundry 테이블 schema 및 data 추가
- [x] Springboot-Mybatis 환경에서의 테스트 코드 작성가능하도록 적절한 Annotation 설정
- [x] TDD를 통해, CRUD 메서드 작성
