### ISSUE TITLE
post-CRUD

### ISSUE THREAD

**Issue by S-HoChan** [Laundry-Platform/Laundry_Core#36]
**Problem or enhancements and It's Background**
- 게시글 데이터를 CRUD하기 위한 작업 수행

**Solutions**
- board interface 내용 수정
- Mapper 파일 내에 알맞은 Query 작성
- 테스트 코드 작성

**TODO Tasks and Cautions**
- [x] interface와 class 구현
- [x] mapper에 Query문 작성
- [x] TDD를 통한 CRUD 메서드 작성
