### ISSUE TITLE
comment-CRUD

### ISSUE THREAD

**Issue by S-HoChan** [Laundry-Platform/Laundry_Core#45]
**Problem or enhancements and It's Background**
- 댓글 데이터를 CRUD하기 위한 작업 수행

**Solutions**
- interface 생성
- query문 작성
- test code 작성

**TODO Tasks and Cautions**
- [ ] Interface와 Class 구현
- [ ] Mapper에 Query문 작성
- [ ] TDD를 통한 CRUD메서드 검증
