### ISSUE TITLE
[회원가입] DTO 설계 및 데이터 DB 에 저장하기

### ISSUE THREAD

**Issue by mankicho** [Laundry-Platform/Laundry_Core#51]
**Problem or enhancements and It's Background**
- 회원가입 요청 시 필요한 데이터를 담는 DTO 설계
- controller - service - repository 로 이어지는 layer 구조 설계

**Solutions**
- 경윤이가 초기 설계한 모델 잘 참조해서 구현해주세요

**TODO Tasks and Cautions**
- [ ] Controller, Service, Repository 클래서 작성
- [ ] Mybatis xml 에 쿼리 작성
- [ ] 필요한 테스트코드 작성하기

**Additional context**

**Comment by Dokyeongyun** [comment]
- #63 이슈에 포함되었습니다.
