### ISSUE TITLE
[회원가입] 시 토큰 발급하기

### ISSUE THREAD

**Issue by mankicho** [Laundry-Platform/Laundry_Core#52]
**Problem or enhancements and It's Background**
- API 통신할때 http 헤더에 토큰값을 담고 요청해야합니다. (참조 : https://www.okta.com/kr/identity-101/what-is-token-based-authentication/)
- 토큰 발급해주는 TokenManager 클래스 설계하기 

**Solutions**
- TokenManager 는 가명이고, 토큰을 관리하는 매니저역할을 하는 객체를 설계하기.

**TODO Tasks and Cautions**
- [ ] 토큰 관련 도메인 이해도 높이기
- [ ] 토큰을 파싱하기위한 개인키값은 어떻게 관리할것인지 잘 고민해보기
- [ ] 필요한 테스트코드 작성

**Additional context**

**Comment by Dokyeongyun** [comment]
@dldmldlsy @newisdom79 
- #61 번 이슈 선행 후 해당 내용 진행 부탁드립니다.
