### ISSUE TITLE
[로그인] 로그인 시 필요한 DTO 모델 설계 및 데이터 DB 에 저장하기

### ISSUE THREAD

**Issue by mankicho** [Laundry-Platform/Laundry_Core#53]
**Problem or enhancements and It's Background**
- 로그인 시 필요한 데이터를 담는 DTO 설계
- controller - service - repository 로 이어지는 layer 구조 설계

**Solutions**
- 경윤이의 초기설계 잘 참조하기

**TODO Tasks and Cautions**
- [ ] Controller, Service, Repository 클래스 작성
- [ ] Mybatis xml 에 쿼리작성
- [ ] 필요한 테스트코드 작성

**Additional context**

**Comment by Dokyeongyun** [comment]
- #63 이슈에 내용 포함되어 close 합니다.
