### ISSUE TITLE
API 문서 자동화 툴 조사

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#56]
**Problem or enhancements and It's Background**
- 노션을 이용한 API 문서작성은 가독성이 상당히 많이 떨어진다..
- 쉽게 접근할 수 있고 공통된 포맷으로 API를 확인하고 싶다.
- 실제 API 개발전 문서화를 먼저 하고 싶다.

**Solutions**
- 요구사항을 충족하는 API 문서 자동화 툴을 조사한다.

**TODO Tasks and Cautions**
- [x] 적합한 API 문서 자동화 툴 조사
- [x] 동시 편집 가능한지 확인
- [x] 접근성, 가독성을 최우선으로 확인

**Comment by Dokyeongyun** [comment]
- **Postman, GitBook** : UI가 깔끔하고 가독성이 좋으며 동시편집이 가능하다. 테스트 요청 전송이 가능하다. **유료**
- **GitBook** : UI가 깔끔하고 가독성이 좋다. 동시편집이 가능하며 버전관리가 가능하다. **유료**
- ﻿**Spring REST docs** : 테스트에 통과해야만 문서화가 가능하여 안정적이지만, 사용법이 상대적으로 복잡하며 실제 API 개발이 이루어져야 문서화가 가능하다.﻿
- ﻿**Google Spreadsheet** : 동시 편집이 가능하나 가독성이 좋지 않다.﻿
- **Slate** : UI 직관적이며 마크다운 기반, 무료
- **Swagger** : RESTful 설계 철학을 강제하며, OpenAPI 스펙을 준수해야 함
