### ISSUE TITLE
빨래방 검색 API 설계 및 구현

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#57]
**Problem or enhancements and It's Background**
- 빨래방 검색 기능 구현을 위해 API 설계 및 구현 필요

**Solutions**
- 빨래방 검색 API 설계 및 구현

**TODO Tasks and Cautions**
- [x] RESTful한 검색 API 설계방법 조사
- [x] 페이징 처리 관련하여 HATEOAS 및 LINK header 조사
- [x] API문서 작성
- [x] DTO 모델 설계
- [x] API 개발

**Additional context**
- 참고문서
    - https://docs.microsoft.com/ko-kr/rest/api/searchservice/search-documents
    - https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/
