### ISSUE TITLE
검색기록 API 설계

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#58]
**Problem or enhancements and It's Background**
- `최근 검색어 보기`, `인기 검색어 보기` 기능을 제공하기 위해 검색기록 API가 필요함

**Solutions**
- 검색기록을 저장할 테이블 스키마 설계
- 회원별 검색기록 C, R, D API 개발

**TODO Tasks and Cautions**
- [ ] 회원별 검색기록 테이블 스키마 설계
- [ ] 전체 검색기록 테이블 스키마 설계
    - 별도로 설계하는게 맞는지 생각해보기
- [ ] 회원별 최근 검색기록 API 설계 및 문서작성
- [ ] 인기검색어 API 설계 및 문서작성

**Comment by Dokyeongyun** [comment]
- 회원별 최근 검색기록 조회, 저장, 삭제 API 설계 및 문서 작성 완료
- 인기검색어 조회 API 설계 및 문서 작성 완료
    - https://hickory-toucan-814.notion.site/503bd065222140b98f5658398c19e507
