### ISSUE TITLE
DB 독립 테스트 환경 구축

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#6]
### Background and Problem
- 프로젝트 초기에는 데이터베이스 스키마의 변동이 많이 발생함.
- 서버 기반 데이터베이스를 사용할 경우, 로컬 개발환경에서 각기 다른 스키마로 개발이 어려움.

### Solutions
- In-Memory or Embedded 데이터베이스를 이용하여 각자 독립된 개발 및 테스트 환경을 구축함.

### TODO & Caution

- [x] H2를 이용한 In-Memory 데이터베이스 개발 환경 구축하기.

- [x] 실제 운영 DB는 MySQL이므로, H2와 MySQL의 쿼리 호환성 체크하기.

- [x] Springboot profile에 따라 개발 중에도 운영 환경으로 실행할 수 있도록 환경 구성하기.

**Comment by Dokyeongyun** [comment]
### Reference
- [H2 한글 인코딩 설정](https://vluevy.tistory.com/42)

**Comment by Dokyeongyun** [comment]
### Pros and Cons
- 장점
    - 외부 영향없는 완벽히 독립적인 데이터베이스 환경 구축
    - 실제 DB 동작여부에 관계없는 테스트 환경 구성 가능
    - 테스트 후 데이터 rollback 필요 없으며, 데이터 무결성 및 정합성 보존
    - Embedded DB로 빠른 테스트 속도
- 단점
    - 실제 DBMS가 H2 가 아닌 경우, 호환성에 대한 문제 발생 가능
    - 스키마가 커지고 데이터가 많아질수록 서버 기동 시 초기화 해야 할 테스트 데이터가 많아짐
