### ISSUE TITLE
회원 인증 방식 조사

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#61]
**Problem or enhancements and It's Background**
- HTTP의 **Connectionless & Stateless**
 특성에 따라 회원을 식별하기 위한 정보를 매 요청 시 전송해주어야 함
- 네트워크를 통해 전달되기 때문에 보안적으로 신경써야 함
- 여러 가지 회원 인증 방식에 대해 조사하고 적절한 회원 인증 방식의 선택이 필요함

**Solutions**
- 회원 인증 방식 조사
    - 특징 및 장단점 파악
    - 대략적인 사용법 파악

**TODO Tasks and Cautions**
- [ ] 각 인증방식의 장단점 파악
- [ ] 사용하기에 적절한 인증방식 선정 및 사용법 조사
- [ ] 팀원들에게 소개 및 설명

**Additional context**
- Reference
    - [백엔드가 이정도는 해줘야 함 - 5. 사용자 인증 방식 결정](https://velog.io/@city7310/%EB%B0%B1%EC%97%94%EB%93%9C%EA%B0%80-%EC%9D%B4%EC%A0%95%EB%8F%84%EB%8A%94-%ED%95%B4%EC%A4%98%EC%95%BC-%ED%95%A8-5.-%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%9D%B8%EC%A6%9D-%EB%B0%A9%EC%8B%9D-%EA%B2%B0%EC%A0%95)
    - [사용자 인증방식의 종류](https://velog.io/@primadonna/%EC%82%AC%EC%9A%A9%EC%9E%90-%EC%9D%B8%EC%A6%9D%EB%B0%A9%EC%8B%9D%EC%9D%98-%EC%A2%85%EB%A5%98)
    - [[Backend] 서버 인증 방식의 종류](https://jeonyoungho.github.io/posts/%EC%84%9C%EB%B2%84-%EC%9D%B8%EC%A6%9D-%EB%B0%A9%EC%8B%9D%EC%9D%98-%EC%A2%85%EB%A5%98/)

**Comment by Dokyeongyun** [comment]
@dldmldlsy 
이 Issue 언제 닫아줄건가요?
