### ISSUE TITLE
[#58 Epic's Child] 회원별 검색기록 API 설계 및 개발

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#67]
**Problem or enhancements and It's Background**
- 회원별 최근 검색어 기능 제공을 위해 API 개발이 필요

**Solutions**
- 회원별 검색기록 조회, 저장, 삭제 API 개발

**TODO Tasks and Cautions**
- [x] 회원별 검색기록 조회 API
- [x] 회원별 검색기록 저장 API
- [x] 회원별 검색기록 삭제 API

**Additional context**
- Epic Issue
    - #58
