### ISSUE TITLE
[#63 Epic's Child] 로그인 API 설계 및 구현

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#70]
**Problem or enhancements and It's Background**
- 개인화된 서비스를 이용하기 위해 로그인 기능이 필요함

**Solutions**
- 로그인 API를 설계 및 구현

**TODO Tasks and Cautions**
- [x] JWT 라이브러리 추가
- [x] BCrypt 라이브러리 추가
- [x] 로그인 API 설계 및 구현

**Additional context**
- Epic Issue
    - #63
