### ISSUE TITLE
각 Layer에서 Validation 로직 분리하기

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#71]
**Problem or enhancements and It's Background**
- 현재는 Controller layer에 클라이언트의 API 요청값에 대한 validation 로직이 포함되어 있다.
- Service Layer에서는 아무런 validation이 이루어지고 있지 않다.
- 각 Layer에 validation 로직을 작성하지 않고 domain model에 constraint를 부여하여 중복된 로직의 제거가 필요하다.

**Solutions**
- Spring validation을 이용하여 domain model에 validation constraint 부여를 통한 유효성 검증 수행

**TODO Tasks and Cautions**
- [x] Bean Validation API 이해하기
- [x] Enum 클래스의 유효성 검증을 위한 Constraint annotaion 커스텀하기
- [x] Controller Layer와 Service Layer 모두에서 Validation 로직이 수행되는지 확인하기
