### ISSUE TITLE
빨래방 방문 리뷰 CRUD API 설계 및 개발

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#74]
**Problem or enhancements and It's Background**
- 방문했던 빨래방에 대한 리뷰 작성 기능이 필요
- 리뷰 제목, 내용, 별점, 사진 등을 입력받음

**Solutions**
- 리뷰 CRUD API 설계 및 개발

**TODO Tasks and Cautions**
- [x] `review` 테이블에 `rating_point` 컬럼 추가
- [x] `review` 테이블 CRUD 메서드 작성 with TDD
- [x] `review` CRUD API 설계 및 개발

**Additional context**
- **[요구사항 정의서](https://www.notion.so/294e3f1e3f794377b0b569db168c5b69)**
- **[UI/UX](https://www.notion.so/294e3f1e3f794377b0b569db168c5b69)**
