### ISSUE TITLE
MyBatis 기본 구조 설계

### ISSUE THREAD

**Issue by Dokyeongyun** [Laundry-Platform/Laundry_Core#8]
**Problem or enhancements and It's Background**
- 사전 회의를 통해 ORM으로 MyBatis를 사용하기로 결정됨.
- 팀원 모두가 동일한 방식으로 MyBatis를 사용할 수 있도록 기본 구조 설계가 필요함.

**Solutions**
- MyBatis와 Repository계층을 연결하는 구조 설계 진행.

**TODO Tasks and Cautions**
- [x] Springboot에서 MyBatis를 사용할 수 있도록 설정
- [x] Repository&Service 계층 생성
- [x] 테스트용 datasource (Embedded H2)를 설정하고 MyBatis 동작 확인

**Comment by Dokyeongyun** [comment]
### Reference
- [MyBatis 설정 참고](https://mybatis.org/mybatis-3/ko/getting-started.html)
